### ISSUE TITLE
Question : how to implement in another python software

### ISSUE THREAD

**Issue by srevinsaju** [seanwu1105/pyqt5-qtquick2-example#3]
I would like to know, how to implement these qtquick theme in my python software https://github.com/srevinsaju/guiscrcpy for your reference. Thanks in advance. It is currently using qt5 without qml, and quick controls

_Sent from my Galaxy Note2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by seanwu1105** [comment]
As for as I know, built-in [QtQuick themes](https://doc.qt.io/qt-5/qtquickcontrols2-styles.html) only support QML with Qt Quick controls. Therefore, you cannot directly apply the themes into Qt widgets.

**Comment by srevinsaju** [comment]
Ok thanks for the info
