### ISSUE TITLE
qrc:/pyqt5_qtquick2_example/qml/main.qml:6:1: module "QtCharts" is not installed

### ISSUE THREAD

**Issue by simplew2011** [seanwu1105/pyqt5-qtquick2-example#4]
qrc:/pyqt5_qtquick2_example/qml/main.qml:6:1: module "QtCharts" is not installed

**Comment by seanwu1105** [comment]
Which version of the Python and PyQt are you using? Please provide further details for me to help you.

**Comment by seanwu1105** [comment]
Close due to inactivity.
